config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'informations#index'

  resources :informations do
    resources :alreadys, only: [:index]
  end
  resources :favorites, only: [:index]

  resources :departments, only: [:index]

  resources :managements

  resources :sales

  resources :productions

  resources :developments

  resource :basic_profile, only: [:show, :edit, :update]
  resource :custom_profile, only: [:edit, :update]
  resources :accounts, only: [:show, :edit, :update]
  resources :user_lists, only: [:index]

  namespace :api, defaults: {format: :json} do
    scope '/informations/:information_id' do
      resource :bookmark, only: [:show, :create, :destroy]
      resource :read, only: [:show, :create, :destroy]
    end

    scope '/managements/:management_id' do
      resources :management_comments, only: [:index, :create]
    end

    scope '/sales/:sale_id' do
      resources :sale_comments, only: [:index, :create]
    end

    scope '/productions/:production_id' do
      resources :production_comments, only: [:index, :create]
    end

    scope '/developments/:development_id' do
      resources :development_comments, only: [:index, :create]
    end
  end
end

app/views/commons/_contact.html.haml
.card_detail
  .card_detail_image
    = link_to account_path(contact.user) do
      = image_tag contact.user.avatar_image
  .card_detail_user
    .card_detail_user_name
      %p= contact.author_name
    .card_detail_user_create
      %p= contact.display_created_at
.card_title
  = contact.title
.card_content
  = contact.content.truncate(35)

app/views/commons/_informations.html.haml
.card#information-index{data: {information_id: information.id}}
  .card_wrap
    .card_detail
      .card_detail_image
        = link_to account_path(information.user) do
          = image_tag information.user.avatar_image
      .card_detail_user
        .card_detail_user_name
          %p= information.author_name
        .card_detail_user_create
          %p= information.display_created_at
      - if current_user.has_bookmark?(information)
        .card_detail_bookmark.active-bookmark{class: "#{information.id}", id: "#{information.id}"}
          = image_tag 'active-bookmark.png'
        .card_detail_bookmark.hidden.inactive-bookmark{class: "#{information.id}", id: "#{information.id}"}
          = image_tag 'bookmark.png'
      - else
        .card_detail_bookmark.inactive-bookmark{class: "#{information.id}", id: "#{information.id}"}
          = image_tag 'bookmark.png'
        .card_detail_bookmark.hidden.active-bookmark{class: "#{information.id}", id: "#{information.id}"}
          = image_tag 'active-bookmark.png'
    .card_title
      = information.title
    .card_content
      %p= information.content.truncate(35)
    .card_display
      = link_to information_path(information) do
        .card_display_button
          %p 詳細を表示
    .card_read
      = link_to information_alreadys_path(information) do
        .card_read_count
          #{information.read_count}人
      %p が既読
      

app/views/commons/_profile.html.haml
.wrap
  = render 'commons/profile_image', user: current_user
  .main
    .container.profilePage
      .profilePage_user
        .profilePage_user_icon
          .profilePage_user_icon_background
            = image_tag user.background_image
            .profilePage_user_icon_image
              = link_to account_path(user) do
                = image_tag user.avatar_image
        .profilePage_user_name
          .profilePage_user_displayName
            = user.display_name
        .profilePage_user_department
          #{I18n.t("enum.departments.#{user.department || 'unentered'}")}
      .profilePage_title
        %h2 基本データ
        %span 基本データは管理者のみが編集可能な情報です。
        - if can? :read, @basic_profile
          - if user == current_user
            .profilePage_adminButton
              = link_to '編集', edit_basic_profile_path
          - else
            .profilePage_adminButton
              = link_to '編集', edit_account_path
      .profilePage_wrap
        .profilePage_wrap_title
          %h3 基本情報
        .profilePage_wrap_content
          .profilePage_wrap_content_type
            %p 氏名
            %p 誕生日
            %p 性別
            %p 所属
          .profilePage_wrap_content_data
            %div
              = user.display_name
            %div
              = user.bday
            %div
              #{I18n.t("enum.genders.#{user.gender || 'unknown'}")}
            %div{class: 'primary-color'}
              #{I18n.t("enum.departments.#{user.department || 'unentered'}")}
      
      .profilePage_title
        %h2 プロフィール
        - if user == current_user
          .profilePage_user_actionButton
            = link_to '編集', edit_custom_profile_path
      .profilePage_wrap
        .profilePage_wrap_title
          %h3 データ
        .profilePage_wrap_content
          .profilePage_wrap_content_type
            %p ニックネーム
            %p 居住地
          .profilePage_wrap_content_data
            %div
              = user&.custom_nickname
            %div
              = user&.custom_birthplace
      .profilePage_wrap
        .profilePage_wrap_title
          %h3 自己紹介
        .profilePage_wrap_introduction
          = user&.custom_introduction

app/views/commons/_profile_image.html.haml
.profile
  .profilePage_user
    .profilePage_user_icon
      .profilePage_user_icon_background
        = image_tag user.background_image
        .profilePage_user_icon_image
          = link_to account_path(user) do
            = image_tag user.avatar_image
    .profilePage_user_name
      .profilePage_user_displayName
        = user.display_name
    .profilePage_user_department
      #{I18n.t("enum.departments.#{user.department || 'unentered'}")}
  .side
    %a{ href: 'http://mail.google.com', target: '_blank', id: 'anchor2' }
      .side_menu
        .side_menu_image
          = image_tag 'Gmail_29991.png'
        .side_menu_text
          %p メール
    .side_line
    = link_to favorites_path do
      .side_menu
        .side_menu_image
          = image_tag 'tag.png'
        .side_menu_text
          %p ブックマーク
    .side_line
    = link_to user_lists_path do
      .side_menu
        .side_menu_image
          = image_tag 's256_f_business_83_0bg.png'
        .side_menu_text
          %p 社員一覧