config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'informations#index'

  resources :informations do
    resources :alreadys, only: [:index]
  end
  resources :favorites, only: [:index]

  resources :departments, only: [:index]

  resources :managements

  resources :sales

  resources :productions

  resources :developments

  resource :basic_profile, only: [:show, :edit, :update]
  resource :custom_profile, only: [:edit, :update]
  resources :accounts, only: [:show, :edit, :update]
  resources :user_lists, only: [:index]

  namespace :api, defaults: {format: :json} do
    scope '/informations/:information_id' do
      resource :bookmark, only: [:show, :create, :destroy]
      resource :read, only: [:show, :create, :destroy]
    end

    scope '/managements/:management_id' do
      resources :management_comments, only: [:index, :create]
    end

    scope '/sales/:sale_id' do
      resources :sale_comments, only: [:index, :create]
    end

    scope '/productions/:production_id' do
      resources :production_comments, only: [:index, :create]
    end

    scope '/developments/:development_id' do
      resources :development_comments, only: [:index, :create]
    end
  end
end

app/models/information.rb
# == Schema Information
#
# Table name: information
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_information_on_user_id  (user_id)
#
class Information < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validate :images_presence

  has_many_attached :images

  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  has_many :reads, dependent: :destroy
  has_many :read_user, through: :reads, source: :user

  def images_presence
    if images.count >= 4
      errors.add(:images, 'は3つまで指定できます')
    end
  end

  def display_created_at
    I18n.l(self.created_at, format: :default)
  end

  def author_name
    user.display_name
  end

  def read_count
    reads.count
  end
end

app/controllers/informations_controller.rb
class InformationsController < ApplicationController
  before_action :authenticate_user!
  before_action :if_not_admin, only: [:new, :create, :edit, :update, :destroy]

  def index
    @informations = Information.all.order(created_at: :desc)
  end

  def show
    @information = Information.find(params[:id])
  end

  def new
    @information = current_user.informations.build
  end

  def create
    @information = current_user.informations.build(information_params)
    if @information.save
      redirect_to information_path(@information), notice: '保存できました'
    else
      flash.now[:error] = '保存に失敗しました'
      render :new
    end
  end

  def edit
    @information = current_user.informations.find(params[:id])
  end

  def update
    @information = current_user.informations.find(params[:id])
    if @information.update(information_params)
      redirect_to information_path(@information), notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  def destroy
    information = current_user.informations.find(params[:id])
    information.destroy!
    redirect_to root_path, notice: '削除に成功しました'
  end

  private
  def information_params
    params.require(:information).permit(:title, :content, images: [])
  end

  private
  def if_not_admin
    redirect_to root_path unless current_user.admin?
  end
end

app/views/informations/edit.html.haml
.container_form
  %ul
    - @information.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @information, url: information_path(@information), method: 'put', local: true) do |f|
    %div
      = f.label :images, '画像'
    %div
      = f.file_field :images,multiple: true
    %div
      = f.label :title, '連絡事項'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    = f.submit '保存', class: 'btn-primary'

app/views/informations/index.html.haml
.wrap
  = render 'commons/profile_image', user: current_user
  .main
    .container
      - if can? :read, @information
        .pageTitleBtn
          = link_to informations_path do
            %h2 全体連絡
          .create
            = link_to new_information_path do
              .create_button
                %p ＋全体連絡作成
      - else
        .pageTitle
          = link_to informations_path do
            %h2 全体連絡
      - @informations.each do |information|
        = render 'commons/informations', information: information

= javascript_pack_tag 'bookmark_index'

app/views/informations/new.html.haml
.container_form
  %ul
    - @information.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @information, url: informations_path, method: 'post', local: true) do |f|
    %div
      = f.label :images, '画像3枚まで'
    %div
      = f.file_field :images,multiple: true
    %div
      = f.label :title, '連絡事項'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    = f.submit '保存', class: 'btn-primary'

app/views/informations/show.html.haml
.wrap
  = render 'commons/profile_image', user: current_user
  .main
    .container
      .pageTitle
        = link_to informations_path do
          %h2 全体連絡
      .information#information-show{data: {information_id: @information.id}}
        .information_wrap
          .information_detail
            .information_detail_image
              = link_to account_path(@information.user) do
                = image_tag @information.user.avatar_image
            .information_detail_user
              .information_detail_user_name
                %p= @information.author_name
              .information_detail_user_create
                %p= @information.display_created_at
            .information_detail_actions
              - if user_signed_in? && current_user.has_information_written?(@information)
                .information_detail_actions_dorpdown
                  .dropdown
                    = image_tag 'actions.svg', class: 'dropbtn'
                    .dropdown-content.mini
                      = link_to '編集する', edit_information_path(@information)
                      = link_to '削除する', information_path(@information), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }
              .information_detail_actions_bookmark.hidden.active-bookmark
                = image_tag 'active-bookmark.png'
              .information_detail_actions_bookmark.hidden.inactive-bookmark
                = image_tag 'bookmark.png'
          - if @information.images.attached?
            - if @information.images.first && @information.images.second && @information.images.third #写真枚数で表示変更
              .information_image_three
                .information_image
                  = image_tag @information.images.first
                .information_image
                  = image_tag @information.images.second
                .information_image
                  = image_tag @information.images.third
            - elsif @information.images.first && @information.images.second
              .information_image_two
                .information_image
                  = image_tag @information.images.first
                .information_image
                  = image_tag @information.images.second
            - else @information.images.first
              .information_image_one
                .information_image
                  = image_tag @information.images.first
          .information_title
            = @information.title
          .information_content
            = @information.content
          .information_read
            .information_read_readButton.hidden.active-read
              %a 既読
            .information_read_inReadButton.hidden.inactive-read
              %a 未読
          .information_userRead
            = link_to information_alreadys_path(@information) do
              .information_userRead_count
                #{@information.read_count}人
            %p が既読

= javascript_pack_tag 'bookmark_show'
= javascript_pack_tag 'read'