config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'informations#index'

  resources :informations do
    resources :alreadys, only: [:index]
  end
  resources :favorites, only: [:index]

  resources :departments, only: [:index]

  resources :managements

  resources :sales

  resources :productions

  resources :developments

  resource :basic_profile, only: [:show, :edit, :update]
  resource :custom_profile, only: [:edit, :update]
  resources :accounts, only: [:show, :edit, :update]
  resources :user_lists, only: [:index]

  namespace :api, defaults: {format: :json} do
    scope '/informations/:information_id' do
      resource :bookmark, only: [:show, :create, :destroy]
      resource :read, only: [:show, :create, :destroy]
    end

    scope '/managements/:management_id' do
      resources :management_comments, only: [:index, :create]
    end

    scope '/sales/:sale_id' do
      resources :sale_comments, only: [:index, :create]
    end

    scope '/productions/:production_id' do
      resources :production_comments, only: [:index, :create]
    end

    scope '/developments/:development_id' do
      resources :development_comments, only: [:index, :create]
    end
  end
end

app/models/sale.rb
# == Schema Information
#
# Table name: sales
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_sales_on_user_id  (user_id)
#
class Sale < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validate :images_presence

  has_many_attached :images

  belongs_to :user
  has_many :sale_comments, dependent: :destroy

  def images_presence
    if images.count >= 4
      errors.add(:images, 'は3つまで指定できます')
    end
  end

  def author_name
    user.display_name
  end

  def display_created_at
    I18n.l(self.created_at, format: :default)
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :authenticate_user!
  before_action :if_not_sale, only: [:new, :create, :edit, :update, :destroy]

  def index
    @sales = Sale.all.order(created_at: :desc)
  end

  def show
    @sale = Sale.find(params[:id])
  end

  def new
    @sale = current_user.sales.build
  end

  def create
    @sale = current_user.sales.build(sale_params)
    if @sale.save
      redirect_to sale_path(@sale), notice: '保存できたました'
    else
      flash.now[:error] = '保存に失敗しました'
      render :new
    end
  end

  def edit
    @sale = current_user.sales.find(params[:id])
  end

  def update
    @sale = current_user.sales.find(params[:id])
    if @sale.update(sale_params)
      redirect_to sale_path(@sale), notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  def destroy
    sale = current_user.sales.find(params[:id])
    sale.destroy!
    redirect_to sales_path, notice: '削除に成功しました'
  end

  private
  def sale_params
    params.require(:sale).permit(:title, :content, images: [])
  end

  private
  def if_not_sale
    redirect_to sales_path unless current_user.department == 'sales'
  end
end

app/views/sales/edit.html.haml
.container_form
  %ul
    - @sale.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @sale, url: sale_path, method: 'put', local: true) do |f|
    %div
      = f.label :images, '画像3枚まで'
    %div
      = f.file_field :images,multiple: true
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    = f.submit '保存', class: 'btn-primary'

app/views/sales/index.html.haml
.wrap
  = render 'commons/profile_image', user: current_user
  .main
    .container
      - if current_user.department == 'sales'
        .pageTitleBtn
          = link_to sales_path do
            %h2 営業部
          .create
            = link_to new_sale_path do
              .create_button
                %p ＋新規ボード作成
      - else
        .pageTitle
          = link_to sales_path do
            %h2 営業部
      - @sales.each do |sale|
        .card
          .card_wrap
            = render 'commons/contact', contact: sale
            .card_display
              = link_to sale_path(sale) do
                .card_display_button
                  %p 詳細を表示

app/views/sales/new.html.haml
.container_form
  %ul
    - @sale.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @sale, url: sales_path, method: 'post', local: true) do |f|
    %div
      = f.label :images, '3枚まで画像添付'
    %div
      = f.file_field :images,multiple: true
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    = f.submit '保存', class: 'btn-primary'

app/views/sales/show.html.haml
.wrap
  = render 'commons/profile_image', user: current_user
  .main
    .container
      .pageTitle
        = link_to sales_path do
          %h2 営業部
      .information#sale-show{data: {sale_id: @sale.id}}
        .information_wrap
          .information_detail
            .information_detail_image
              = link_to account_path(@sale.user) do
                = image_tag @sale.user.avatar_image
            .information_detail_user
              .information_detail_user_name
                %p= @sale.author_name
              .information_detail_user_create
                %p= @sale.display_created_at
            .information_detail_actions
              - if user_signed_in? && current_user.has_sale_written?(@sale)
                .information_detail_actions_dorpdown
                  .dropdown
                    = image_tag 'actions.svg', class: 'dropbtn'
                    .dropdown-content.mini
                      = link_to '編集する', edit_sale_path(@sale)
                      = link_to '削除する', sale_path(@sale), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }
          - if @sale.images.attached?
            - if @sale.images.first && @sale.images.second && @sale.images.third
              .information_image_three
                .information_image
                  = image_tag @sale.images.first
                .information_image
                  = image_tag @sale.images.second
                .information_image
                  = image_tag @sale.images.third
            - elsif @sale.images.first && @sale.images.second
              .information_image_two
                .information_image
                  = image_tag @sale.images.first
                .information_image
                  = image_tag @sale.images.second
            - else @sale.images.first
              .information_image_one
                .information_image
                  = image_tag @sale.images.first
          .information_title
            = @sale.title
          .information_content
            = @sale.content
    .container
      .pageTitle
        %h3 コメント
      .sale-comment-container

    - if current_user.department == 'sales'
      .container
        .btn-secondary.sale-comment-form
          コメントを追加
        .comment-text-area.hidden
          = text_area_tag :comment_content, '', class: 'sm'
          .btn-secondary.add-comment-button
            コメントを追加

= javascript_pack_tag 'sale_comment'