config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'informations#index'

  resources :informations do
    resources :alreadys, only: [:index]
  end
  resources :favorites, only: [:index]

  resources :departments, only: [:index]

  resources :managements

  resources :sales

  resources :productions

  resources :developments

  resource :basic_profile, only: [:show, :edit, :update]
  resource :custom_profile, only: [:edit, :update]
  resources :accounts, only: [:show, :edit, :update]
  resources :user_lists, only: [:index]

  namespace :api, defaults: {format: :json} do
    scope '/informations/:information_id' do
      resource :bookmark, only: [:show, :create, :destroy]
      resource :read, only: [:show, :create, :destroy]
    end

    scope '/managements/:management_id' do
      resources :management_comments, only: [:index, :create]
    end

    scope '/sales/:sale_id' do
      resources :sale_comments, only: [:index, :create]
    end

    scope '/productions/:production_id' do
      resources :production_comments, only: [:index, :create]
    end

    scope '/developments/:development_id' do
      resources :development_comments, only: [:index, :create]
    end
  end
end

app/models/management.rb
# == Schema Information
#
# Table name: managements
#
#  id         :bigint           not null, primary key
#  content    :text             not null
#  title      :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_managements_on_user_id  (user_id)
#
class Management < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validate :images_presence

  has_many_attached :images

  belongs_to :user
  has_many :management_comments, dependent: :destroy

  def images_presence
    if images.count >= 4
      errors.add(:images, 'は3つまで指定できます')
    end
  end

  def author_name
    user.display_name
  end

  def display_created_at
    I18n.l(self.created_at, format: :default)
  end
end

app/controllers/managements_controller.rb
class ManagementsController < ApplicationController
  before_action :authenticate_user!
  before_action :if_not_management, only: [:new, :create, :edit, :update, :destroy]

  def index
    @managements = Management.all.order(created_at: :desc)
  end

  def show
    @management = Management.find(params[:id])
  end

  def new
    @management = current_user.managements.build
  end

  def create
    @management = current_user.managements.build(management_params)
    if @management.save
      redirect_to management_path(@management), notice: '保存できました'
    else
      flash.now[:error] = '保存に失敗しました'
      render :new
    end
  end

  def edit
    @management = current_user.managements.find(params[:id])
  end

  def update
    @management = current_user.managements.find(params[:id])
    if @management.update(management_params)
      redirect_to management_path(@management), notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit
    end
  end

  def destroy
    management = current_user.managements.find(params[:id])
    management.destroy!
    redirect_to managements_path, notice: '削除に成功しました'
  end

  private
  def management_params
    params.require(:management).permit(:title, :content, images: [])
  end

  private
  def if_not_management
    redirect_to managements_path unless current_user.department == 'management'
  end
end

app/views/managements/edit.html.haml
.container_form
  %ul
    - @management.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @management, url: management_path, method: 'put', local: true) do |f|
    %div
      = f.label :images, '画像3枚まで'
    %div
      = f.file_field :images,multiple: true
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    = f.submit '保存', class: 'btn-primary'

app/views/managements/index.html.haml
.wrap
  = render 'commons/profile_image', user: current_user
  .main
    .container
      - if current_user.department == 'management'
        .pageTitleBtn
          = link_to managements_path do
            %h2 経営陣
          .create
            = link_to new_management_path do
              .create_button
                %p ＋新規ボード作成
      - else
        .pageTitle
          = link_to managements_path do
            %h2 経営陣
      - @managements.each do |management|
        .card
          .card_wrap
            = render 'commons/contact', contact: management
            .card_display
              = link_to management_path(management) do
                .card_display_button
                  %p 詳細を表示

app/views/managements/new.html.haml
.container_form
  %ul
    - @management.errors.full_messages.each do |message|
      %li= message

  = form_with(model: @management, url: managements_path, method: 'post', local: true) do |f|
    %div
      = f.label :images, '画像'
    %div
      = f.file_field :images,multiple: true
    %div
      = f.label :title, 'タイトル'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :content, '内容'
    %div
      = f.text_area :content
    = f.submit '保存', class: 'btn-primary'

app/views/managements/show.html.haml
.wrap
  = render 'commons/profile_image', user: current_user
  .main
    .container
      .pageTitle
        = link_to managements_path do
          %h2 経営陣
      .information#management-show{data: {management_id: @management.id}}
        .information_wrap
          .information_detail
            .information_detail_image
              = link_to account_path(@management.user) do
                = image_tag @management.user.avatar_image
            .information_detail_user
              .information_detail_user_name
                %p= @management.author_name
              .information_detail_user_create
                %p= @management.display_created_at
            .information_detail_actions
              - if user_signed_in? && current_user.has_management_written?(@management)
                .information_detail_actions_dorpdown
                  .dropdown
                    = image_tag 'actions.svg', class: 'dropbtn'
                    .dropdown-content.mini
                      = link_to '編集する', edit_management_path(@management)
                      = link_to '削除する', management_path(@management), data: { method: 'delete', confirm: '本当に削除してもよろしいですか？' }
          - if @management.images.attached?
            - if @management.images.first && @management.images.second && @management.images.third
              .information_image_three
                .information_image
                  = image_tag @management.images.first
                .information_image
                  = image_tag @management.images.second
                .information_image
                  = image_tag @management.images.third
            - elsif @management.images.first && @management.images.second
              .information_image_two
                .information_image
                  = image_tag @management.images.first
                .information_image
                  = image_tag @management.images.second
            - else @management.images.first
              .information_image_one
                .information_image
                  = image_tag @management.images.first
          .information_title
            = @management.title
          .information_content
            = @management.content
    .container
      .pageTitle
        %h3 コメント
      .management-comment-container

    - if current_user.department == 'management'
      .container
        .btn-secondary.management-comment-form
          コメントを追加
        .comment-text-area.hidden
          = text_area_tag :comment_content, '', class: 'sm'
          .btn-secondary.add-comment-button
            コメントを追加

= javascript_pack_tag 'management_comment'